# Generated by Django 5.2.1 on 2025-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons', models.CharField(max_length=250, verbose_name='Short review')),
                ('full_text', models.TextField(verbose_name='Review full text')),
                ('date', models.DateTimeField(verbose_name='Publish date')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
