# Generated by Django 5.2.1 on 2025-05-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articale', 'verbose_name_plural': 'Articles'},
        ),
    ]
